//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class CibleInfoResponse : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/CibleInfo";
        public override string RosMessageName => k_RosMessageName;

        public string identite;
        public string qrcode;
        public float statut;
        public float rayon_secu;
        public string desactivation;
        public string lima;

        public CibleInfoResponse()
        {
            this.identite = "";
            this.qrcode = "";
            this.statut = 0.0f;
            this.rayon_secu = 0.0f;
            this.desactivation = "";
            this.lima = "";
        }

        public CibleInfoResponse(string identite, string qrcode, float statut, float rayon_secu, string desactivation, string lima)
        {
            this.identite = identite;
            this.qrcode = qrcode;
            this.statut = statut;
            this.rayon_secu = rayon_secu;
            this.desactivation = desactivation;
            this.lima = lima;
        }

        public static CibleInfoResponse Deserialize(MessageDeserializer deserializer) => new CibleInfoResponse(deserializer);

        private CibleInfoResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.identite);
            deserializer.Read(out this.qrcode);
            deserializer.Read(out this.statut);
            deserializer.Read(out this.rayon_secu);
            deserializer.Read(out this.desactivation);
            deserializer.Read(out this.lima);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.identite);
            serializer.Write(this.qrcode);
            serializer.Write(this.statut);
            serializer.Write(this.rayon_secu);
            serializer.Write(this.desactivation);
            serializer.Write(this.lima);
        }

        public override string ToString()
        {
            return "CibleInfoResponse: " +
            "\nidentite: " + identite.ToString() +
            "\nqrcode: " + qrcode.ToString() +
            "\nstatut: " + statut.ToString() +
            "\nrayon_secu: " + rayon_secu.ToString() +
            "\ndesactivation: " + desactivation.ToString() +
            "\nlima: " + lima.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
