//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Pol
{
    [Serializable]
    public class SpatialDataMsg : Message
    {
        public const string k_RosMessageName = "pol_msgs/SpatialData";
        public override string RosMessageName => k_RosMessageName;

        public SpatialPointMsg[] points;

        public SpatialDataMsg()
        {
            this.points = new SpatialPointMsg[0];
        }

        public SpatialDataMsg(SpatialPointMsg[] points)
        {
            this.points = points;
        }

        public static SpatialDataMsg Deserialize(MessageDeserializer deserializer) => new SpatialDataMsg(deserializer);

        private SpatialDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.points, SpatialPointMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.points);
            serializer.Write(this.points);
        }

        public override string ToString()
        {
            return "SpatialDataMsg: " +
            "\npoints: " + System.String.Join(", ", points.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
