//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Pol
{
    [Serializable]
    public class SpatialPointMsg : Message
    {
        public const string k_RosMessageName = "pol_msgs/SpatialPoint";
        public override string RosMessageName => k_RosMessageName;

        public int x;
        public int y;
        public int z;
        public byte color_r;
        public byte color_g;
        public byte color_b;
        public byte color_a;
        public float timestamp;

        public SpatialPointMsg()
        {
            this.x = 0;
            this.y = 0;
            this.z = 0;
            this.color_r = 0;
            this.color_g = 0;
            this.color_b = 0;
            this.color_a = 0;
            this.timestamp = 0.0f;
        }

        public SpatialPointMsg(int x, int y, int z, byte color_r, byte color_g, byte color_b, byte color_a, float timestamp)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.color_r = color_r;
            this.color_g = color_g;
            this.color_b = color_b;
            this.color_a = color_a;
            this.timestamp = timestamp;
        }

        public static SpatialPointMsg Deserialize(MessageDeserializer deserializer) => new SpatialPointMsg(deserializer);

        private SpatialPointMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.color_r);
            deserializer.Read(out this.color_g);
            deserializer.Read(out this.color_b);
            deserializer.Read(out this.color_a);
            deserializer.Read(out this.timestamp);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.color_r);
            serializer.Write(this.color_g);
            serializer.Write(this.color_b);
            serializer.Write(this.color_a);
            serializer.Write(this.timestamp);
        }

        public override string ToString()
        {
            return "SpatialPointMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\ncolor_r: " + color_r.ToString() +
            "\ncolor_g: " + color_g.ToString() +
            "\ncolor_b: " + color_b.ToString() +
            "\ncolor_a: " + color_a.ToString() +
            "\ntimestamp: " + timestamp.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
