//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class CibleInfoRequest : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/CibleInfo";
        public override string RosMessageName => k_RosMessageName;

        //  CibleInfo.srv
        //  Request message
        public float latitude;
        public float longitude;
        //  Response message

        public CibleInfoRequest()
        {
            this.latitude = 0.0f;
            this.longitude = 0.0f;
        }

        public CibleInfoRequest(float latitude, float longitude)
        {
            this.latitude = latitude;
            this.longitude = longitude;
        }

        public static CibleInfoRequest Deserialize(MessageDeserializer deserializer) => new CibleInfoRequest(deserializer);

        private CibleInfoRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.latitude);
            deserializer.Read(out this.longitude);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.latitude);
            serializer.Write(this.longitude);
        }

        public override string ToString()
        {
            return "CibleInfoRequest: " +
            "\nlatitude: " + latitude.ToString() +
            "\nlongitude: " + longitude.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
